### PR TITLE
Create Low Battery Things

### PR DESCRIPTION
**Pull request by fortepc**

### CODE REVIEW

**Comment by ludeeus** [comment]
@fortepc Could you add a picture of how it could look?
Without that, it would just be the same (basically) that is on the repo for that card

**Comment by fortepc** [comment]
Yes! Sorry I thought I did. I'll get that ~~today~~ sometime.

**Review by fortepc — COMMENTED** [review]
Added an image, and updated the card config to be better.

**Review by swetoast — APPROVED** [review]

**Comment by fortepc** [comment]
Yay! :D

**Pull request merged**
